### ISSUE TITLE
After landing, the icon that opens and closes the sound is the icon that closes the sound.	failed，When the last user left, the sound Icon was the open Icon

### ISSUE THREAD

**Issue by cisco6** [OpenVisualCloud/Video-Conferencing-Sample#17]
After landing, the   icon that opens and closes the sound is the icon that closes the sound. | failed，When the last user left, the sound   Icon was the open Icon
-- | --

**Comment by qwu16** [comment]
duplicate with bug 11

**Comment by cisco6** [comment]
1. User 1 logs in to the meeting

2. User 2 login meeting

3. User 1 opens the lower right corner to speak

4. User 1 leaves the room

5. User 1 enters the room immediately. The icon in the lower right corner opens the sound, but there is no sound.
