### ISSUE TITLE
Share screen process will not work well if 2 users are sharing screen at the same time. 

### ISSUE THREAD

**Issue by cisco6** [OpenVisualCloud/Video-Conferencing-Sample#18]
After login, the   shared screen is normal  with  audio and video | pass,But when you click on the Shared   Screen icon, the Shared Screen disappears.
-- | --

**Comment by cisco6** [comment]
1. User 1 logs in to the meeting

2. User 2 login meeting

3. User 1 Shares Screen

4, User 2, Receiving the Shared Screen, Click on the Shared Screen icon in the bottom left and right corner. When the Shared Screen disappears, there is no way to retrieve the Shared Screen.

**Comment by qwu16** [comment]
We need to modify scenario to only one share screen allowed.

**Comment by starwarfan** [comment]
Only one screen-sharing stream is allowed
